//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.03 at 12:27:56 AM GMT-03:00 
//

package br.com.nordestefomento.texgit.language;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * 
 * <p>
 * Instrumento utilizado para preencher um field com um formato e caracteres pr�
 * definidos.
 * </p>
 * 
 * 
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetaFiller")
public class MetaFiller {

	@XmlAttribute(required = true)
	protected String padding;
	@XmlAttribute
	protected EnumSide sideToFill;

	/**
	 * Gets the value of the padding property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPadding() {
		return padding;
	}

	/**
	 * Sets the value of the padding property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPadding(String value) {
		this.padding = value;
	}

	/**
	 * Gets the value of the sideToFill property.
	 * 
	 * @return possible object is {@link EnumSide }
	 * 
	 */
	public EnumSide getSideToFill() {
		if (sideToFill == null) {
			return EnumSide.LEFT;
		} else {
			return sideToFill;
		}
	}

	/**
	 * Sets the value of the sideToFill property.
	 * 
	 * @param value
	 *            allowed object is {@link EnumSide }
	 * 
	 */
	public void setSideToFill(EnumSide value) {
		this.sideToFill = value;
	}

}
