//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.03 at 12:27:56 AM GMT-03:00 
//

package org.jrimum.texgit.language;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * 
 * 
 * <p>
 * Agregado de fields.
 * </p>
 * 
 * 
 * 
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetaGroupFields", propOrder = { "idType", "fields",
		"sequencialNumber" })
public class MetaGroupFields {

	@XmlElement(name = "IdType", required = true)
	protected MetaOrderedField idType;
	@XmlElement(name = "Field", required = true)
	protected List<MetaField> fields;
	@XmlElement(name = "SequencialNumber")
	protected MetaOrderedField sequencialNumber;

	/**
	 * Gets the value of the idType property.
	 * 
	 * @return possible object is {@link MetaOrderedField }
	 * 
	 */
	public MetaOrderedField getIdType() {
		return idType;
	}

	/**
	 * Sets the value of the idType property.
	 * 
	 * @param value
	 *            allowed object is {@link MetaOrderedField }
	 * 
	 */
	public void setIdType(MetaOrderedField value) {
		this.idType = value;
	}

	/**
	 * Gets the value of the fields property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the fields property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFields().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link MetaField }
	 * 
	 * 
	 */
	public List<MetaField> getFields() {
		if (fields == null) {
			fields = new ArrayList<MetaField>();
		}
		return this.fields;
	}

	/**
	 * Gets the value of the sequencialNumber property.
	 * 
	 * @return possible object is {@link MetaOrderedField }
	 * 
	 */
	public MetaOrderedField getSequencialNumber() {
		return sequencialNumber;
	}

	/**
	 * Sets the value of the sequencialNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link MetaOrderedField }
	 * 
	 */
	public void setSequencialNumber(MetaOrderedField value) {
		this.sequencialNumber = value;
	}

	@SuppressWarnings("serial")
	public static class IdType extends JAXBElement<MetaOrderedField> {

		protected final static QName NAME = new QName("", "IdType");

		@SuppressWarnings("unchecked")
		public IdType(MetaOrderedField value) {
			super(NAME, ((Class) MetaOrderedField.class),
					MetaGroupFields.class, value);
		}

	}

	@SuppressWarnings("serial")
	public static class SequencialNumber extends JAXBElement<MetaOrderedField> {

		protected final static QName NAME = new QName("", "SequencialNumber");

		@SuppressWarnings("unchecked")
		public SequencialNumber(MetaOrderedField value) {
			super(NAME, ((Class) MetaOrderedField.class),
					MetaGroupFields.class, value);
		}

	}

}
