//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.23 at 09:35:40 PM GMT-03:00 
//


package texgit.language;

import javax.xml.bind.annotation.XmlEnum;


/**
 * 
 * 						
 * 					<p>
 * 						Basicamente são definições de direções de
 * 						escrita e leitura.
 * 					</p>
 * 					
 * 					
 * 
 * <p>Java class for enumSide.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumSide">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LEFT"/>
 *     &lt;enumeration value="RIGHT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum EnumSide {

    LEFT,
    RIGHT;

    public String value() {
        return name();
    }

    public static EnumSide fromValue(String v) {
        return valueOf(v);
    }

}
