//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.03 at 12:27:56 AM GMT-03:00 
//


package texgit.language;

import javax.xml.bind.annotation.XmlEnum;


/**
 * 
 * 						
 * 					<p>
 * 						Tipo de formatadores suportados. Usados junto a
 * 						definição de novos formatadores.
 * 					</p>
 * 					
 * 					
 * 
 * <p>Java class for enumFormatsTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumFormatsTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DATE"/>
 *     &lt;enumeration value="DECIMAL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum EnumFormatsTypes {

    DATE,
    DECIMAL;

    public String value() {
        return name();
    }

    public static EnumFormatsTypes fromValue(String v) {
        return valueOf(v);
    }

}
