//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.23 at 09:35:40 PM GMT-03:00 
//


package texgit.language;

import javax.xml.bind.annotation.XmlEnum;


/**
 * 
 * 						
 * 					<p>
 * 						Formatos pré definidos suportados pelo
 * 						componente.
 * 					</p>
 * 					
 * 					
 * 
 * <p>Java class for enumFormats.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enumFormats">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DATE_DDMMYY"/>
 *     &lt;enumeration value="DATE_DDMMYYYY"/>
 *     &lt;enumeration value="DATE_YYMMDD"/>
 *     &lt;enumeration value="DATE_YYYYMMDD"/>
 *     &lt;enumeration value="DECIMAL_D"/>
 *     &lt;enumeration value="DECIMAL_DD"/>
 *     &lt;enumeration value="DECIMAL_DDD"/>
 *     &lt;enumeration value="DECIMAL_DDDD"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum EnumFormats {

    DATE_DDMMYY,
    DATE_DDMMYYYY,
    DATE_YYMMDD,
    DATE_YYYYMMDD,
    DECIMAL_D,
    DECIMAL_DD,
    DECIMAL_DDD,
    DECIMAL_DDDD;

    public String value() {
        return name();
    }

    public static EnumFormats fromValue(String v) {
        return valueOf(v);
    }

}
