//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.23 at 09:35:40 PM GMT-03:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://gilmatryx.googlepages.com/Texgit")
package texgit.language;
