/*
 * Copyright 2008 JRimum Project
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by
 * applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
 * OF ANY KIND, either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 * 
 * Created at: 03/08/2008 - 12:27:56
 * 
 * ================================================================================
 * 
 * Direitos autorais 2008 JRimum Project
 * 
 * Licenciado sob a Licença Apache, Versão 2.0 ("LICENÇA"); você não pode usar
 * esse arquivo exceto em conformidade com a esta LICENÇA. Você pode obter uma
 * cópia desta LICENÇA em http://www.apache.org/licenses/LICENSE-2.0 A menos que
 * haja exigência legal ou acordo por escrito, a distribuição de software sob
 * esta LICENÇA se dará “COMO ESTÁ”, SEM GARANTIAS OU CONDIÇÕES DE QUALQUER
 * TIPO, sejam expressas ou tácitas. Veja a LICENÇA para a redação específica a
 * reger permissões e limitações sob esta LICENÇA.
 * 
 * Criado em: 03/08/2008 - 12:27:56
 * 
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.03 at 12:27:56 AM GMT-03:00 
//

package org.jrimum.texgit.language;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

/**
 * 
 * 
 * <p>
 * Agregado de fields.
 * </p>
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MetaGroupFields", propOrder = { "idType", "fields",
		"sequencialNumber" })
public class MetaGroupFields {

	@XmlElement(name = "IdType", required = true)
	protected MetaOrderedField idType;
	@XmlElement(name = "Field", required = true)
	protected List<MetaField> fields;
	@XmlElement(name = "SequencialNumber")
	protected MetaOrderedField sequencialNumber;

	/**
	 * Gets the value of the idType property.
	 * 
	 * @return possible object is {@link MetaOrderedField }
	 * 
	 */
	public MetaOrderedField getIdType() {
		return idType;
	}

	/**
	 * Sets the value of the idType property.
	 * 
	 * @param value
	 *            allowed object is {@link MetaOrderedField }
	 * 
	 */
	public void setIdType(MetaOrderedField value) {
		this.idType = value;
	}

	/**
	 * Gets the value of the fields property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the fields property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFields().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link MetaField }
	 * 
	 * 
	 */
	public List<MetaField> getFields() {
		if (fields == null) {
			fields = new ArrayList<MetaField>();
		}
		return this.fields;
	}

	/**
	 * Gets the value of the sequencialNumber property.
	 * 
	 * @return possible object is {@link MetaOrderedField }
	 * 
	 */
	public MetaOrderedField getSequencialNumber() {
		return sequencialNumber;
	}

	/**
	 * Sets the value of the sequencialNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link MetaOrderedField }
	 * 
	 */
	public void setSequencialNumber(MetaOrderedField value) {
		this.sequencialNumber = value;
	}

	public static class IdType extends JAXBElement<MetaOrderedField> {

		/**
		 * {@code serialVersionUID = -8934480908648452108L}
		 */
		private static final long serialVersionUID = -8934480908648452108L;
		
		protected final static QName NAME = new QName("", "IdType");

		public IdType(MetaOrderedField value) {
			super(NAME, ((Class<MetaOrderedField>) MetaOrderedField.class),
					MetaGroupFields.class, value);
		}

	}

	public static class SequencialNumber extends JAXBElement<MetaOrderedField> {

		/**
		 * {@code serialVersionUID = 3923837730914132777L}
		 */
		private static final long serialVersionUID = 3923837730914132777L;
		
		protected final static QName NAME = new QName("", "SequencialNumber");

		public SequencialNumber(MetaOrderedField value) {
			super(NAME, ((Class<MetaOrderedField>) MetaOrderedField.class),
					MetaGroupFields.class, value);
		}

	}

}
