/*
 * Copyright 2008 JRimum Project
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by
 * applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS
 * OF ANY KIND, either express or implied. See the License for the specific
 * language governing permissions and limitations under the License.
 * 
 * Created at: 03/08/2008 - 12:27:56
 * 
 * ================================================================================
 * 
 * Direitos autorais 2008 JRimum Project
 * 
 * Licenciado sob a Licença Apache, Versão 2.0 ("LICENÇA"); você não pode usar
 * esse arquivo exceto em conformidade com a esta LICENÇA. Você pode obter uma
 * cópia desta LICENÇA em http://www.apache.org/licenses/LICENSE-2.0 A menos que
 * haja exigência legal ou acordo por escrito, a distribuição de software sob
 * esta LICENÇA se dará “COMO ESTÁ”, SEM GARANTIAS OU CONDIÇÕES DE QUALQUER
 * TIPO, sejam expressas ou tácitas. Veja a LICENÇA para a redação específica a
 * reger permissões e limitações sob esta LICENÇA.
 * 
 * Criado em: 03/08/2008 - 12:27:56
 * 
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.08.03 at 12:27:56 AM GMT-03:00 
//

package org.jrimum.texgit.language;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the texgit.language package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName TEXGIT_QNAME = new QName(
			"http://jrimum.org/texgit", "Texgit");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: texgit.language
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link MetaField }
	 * 
	 */
	public MetaField createMetaField() {
		return new MetaField();
	}

	/**
	 * Create an instance of {@link MetaFlatFile }
	 * 
	 */
	public MetaFlatFile createMetaFlatFile() {
		return new MetaFlatFile();
	}

	/**
	 * Create an instance of {@link MetaOrderedField }
	 * 
	 */
	public MetaOrderedField createMetaOrderedField() {
		return new MetaOrderedField();
	}

	/**
	 * Create an instance of {@link MetaRecord }
	 * 
	 */
	public MetaRecord createMetaRecord() {
		return new MetaRecord();
	}

	/**
	 * Create an instance of {@link MetaLayout }
	 * 
	 */
	public MetaLayout createMetaLayout() {
		return new MetaLayout();
	}

	/**
	 * Create an instance of {@link MetaTexgit }
	 * 
	 */
	public MetaTexgit createMetaTexgit() {
		return new MetaTexgit();
	}

	/**
	 * Create an instance of {@link MetaFormatter }
	 * 
	 */
	public MetaFormatter createMetaFormatter() {
		return new MetaFormatter();
	}

	/**
	 * Create an instance of {@link MetaGroupFields }
	 * 
	 */
	public MetaGroupFields createMetaGroupFields() {
		return new MetaGroupFields();
	}

	/**
	 * Create an instance of {@link MetaGroupRecords }
	 * 
	 */
	public MetaGroupRecords createMetaGroupRecords() {
		return new MetaGroupRecords();
	}

	/**
	 * Create an instance of {@link MetaFiller }
	 * 
	 */
	public MetaFiller createMetaFiller() {
		return new MetaFiller();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link MetaTexgit }{@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "http://jrimum.org/texgit", name = "Texgit")
	public JAXBElement<MetaTexgit> createTexgit(MetaTexgit value) {
		return new JAXBElement<MetaTexgit>(TEXGIT_QNAME, MetaTexgit.class,
				null, value);
	}

	/**
	 * Create an instance of {@link MetaGroupFields.SequencialNumber }}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "SequencialNumber", scope = MetaGroupFields.class)
	public MetaGroupFields.SequencialNumber createMetaGroupFieldsSequencialNumber(
			MetaOrderedField value) {
		return new MetaGroupFields.SequencialNumber(value);
	}

	/**
	 * Create an instance of {@link MetaGroupFields.IdType }}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IdType", scope = MetaGroupFields.class)
	public MetaGroupFields.IdType createMetaGroupFieldsIdType(
			MetaOrderedField value) {
		return new MetaGroupFields.IdType(value);
	}

}
